model:
  type: diffusion 
  network: dualenc
  hidden_dim: 128
  num_convs: 6
  num_convs_local: 4
  cutoff: 10.0
  mlp_act: relu
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  num_diffusion_timesteps: 100
  edge_order: 3
  edge_encoder: mlp
  smooth_conv: false
  gamma_schedule_type: exp_inc  # or "linear" / "exp_inc" / "exp_dec" / "cosine" / "sqrt" / "sigmoid"
  # noise_ratio: 0.3

train:
  seed: 2021
  batch_size: 64
  val_freq: 5000
  max_iters: 120000
  max_grad_norm: 10000.0
  anneal_power: 2.0
  optimizer:
    type: adam
    lr: 1.e-3
    weight_decay: 0.
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 10

dataset:
  train: ./data/uncondition/QM9/train_data.pkl
  val: ./data/uncondition/QM9/val_data.pkl
  test: ./data/uncondition/QM9/test_data.pkl
